import type { Config } from "tailwindcss";
import animatePlugin from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-pill": ["Inter"],
        "headline-md": ["Manrope"],
        "headline-sm": ["Manrope"],
        "display-lg": ["Manrope"],
        "data-tabular": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-pill": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "data-tabular": ["14px", { "lineHeight": "1.2", "fontWeight": "500" }]
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        source: {
          gym: "hsl(var(--source-gym))",
          pack: "hsl(var(--source-pack))",
          floor: "hsl(var(--source-floor))",
          referral: "hsl(var(--source-referral))",
          social: "hsl(var(--source-social))",
        },
        stage: {
          lead: "hsl(var(--stage-lead))",
          nurture: "hsl(var(--stage-nurture))",
          trial: "hsl(var(--stage-trial))",
          pitch: "hsl(var(--stage-pitch))",
          won: "hsl(var(--stage-won))",
          lost: "hsl(var(--stage-lost))",
        },
        "on-primary-container": "hsl(var(--on-primary-container))",
        "surface-tint": "hsl(var(--surface-tint))",
        "inverse-on-surface": "hsl(var(--inverse-on-surface))",
        "secondary-container": "hsl(var(--secondary-container))",
        "tertiary-fixed": "hsl(var(--tertiary-fixed))",
        "surface-container": "hsl(var(--surface-container))",
        "outline-variant": "hsl(var(--outline-variant))",
        "on-surface": "hsl(var(--on-surface))",
        "tertiary-container": "hsl(var(--tertiary-container))",
        "on-tertiary-fixed": "hsl(var(--on-tertiary-fixed))",
        "surface-variant": "hsl(var(--surface-variant))",
        "secondary-fixed-dim": "hsl(var(--secondary-fixed-dim))",
        "tertiary-fixed-dim": "hsl(var(--tertiary-fixed-dim))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        "primary-fixed": "hsl(var(--primary-fixed))",
        "on-secondary-fixed": "hsl(var(--on-secondary-fixed))",
        "error": "hsl(var(--error))",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "surface-bright": "hsl(var(--surface-bright))",
        "secondary-fixed": "hsl(var(--secondary-fixed))",
        "on-secondary": "hsl(var(--on-secondary))",
        "error-container": "hsl(var(--error-container))",
        "surface-dim": "hsl(var(--surface-dim))",
        "on-secondary-fixed-variant": "hsl(var(--on-secondary-fixed-variant))",
        "outline": "hsl(var(--outline))",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "on-tertiary-container": "hsl(var(--on-tertiary-container))",
        "on-primary-fixed-variant": "hsl(var(--on-primary-fixed-variant))",
        "on-primary-fixed": "hsl(var(--on-primary-fixed))",
        "on-tertiary": "hsl(var(--on-tertiary))",
        "on-background": "hsl(var(--on-background))",
        "tertiary": "hsl(var(--tertiary))",
        "inverse-surface": "hsl(var(--inverse-surface))",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        "on-tertiary-fixed-variant": "hsl(var(--on-tertiary-fixed-variant))",
        "on-secondary-container": "hsl(var(--on-secondary-container))",
        "on-primary": "hsl(var(--on-primary))",
        "inverse-primary": "hsl(var(--inverse-primary))",
        "surface": "hsl(var(--surface))",
        "primary-container": "hsl(var(--primary-container))",
        "on-error": "hsl(var(--on-error))",
        "primary-fixed-dim": "hsl(var(--primary-fixed-dim))",
        "on-error-container": "hsl(var(--on-error-container))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "slide-up": { "0%": { transform: "translateY(100%)" }, "100%": { transform: "translateY(0)" } },
        "pulse-glow": { "0%,100%": { boxShadow: "0 0 0 0 hsl(var(--primary) / 0.5)" }, "50%": { boxShadow: "0 0 0 12px hsl(var(--primary) / 0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "slide-up": "slide-up 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [animatePlugin],
} satisfies Config;
